### ISSUE TITLE
DISEÑO DE LOGOTIPO

### ISSUE THREAD

**Issue by EdwinJaraOFC** [EdwinJaraOFC/VentusSolarisAnalyzer#20]
- [x]  Diseño finalizado del logotipo, que será utilizado en materiales de difusión.
- [x]  Representa visualmente la identidad del proyecto VentusSolaris.
- [x]  El logotipo será empleado en la página web, folletos y póster del proyecto.

**Comment by RominaPerezAmado** [comment]
Listo
